services:
  rw-tg-shop-chap:
    image: ghcr.io/chapaayy/rw-tg-shop-chap:latest
    pull_policy: always
    container_name: rw-tg-shop-chap
    hostname: rw-tg-shop-chap
    env_file:
      - .env
    networks:
      - remnawave-network
    restart: unless-stopped
    depends_on:
      rw-tg-shop-chap-db:
        condition: service_healthy
      rw-tg-shop-chap-redis:
        condition: service_healthy

  rw-tg-shop-chap-db:
    image: postgres:17
    container_name: rw-tg-shop-chap-db
    hostname: rw-tg-shop-chap-db
    env_file:
      - .env
    volumes:
      - rw-tg-shop-chap-db-data:/var/lib/postgresql/data
    networks:
      - remnawave-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

  rw-tg-shop-chap-redis:
    image: redis:7-alpine
    container_name: rw-tg-shop-chap-redis
    hostname: rw-tg-shop-chap-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - rw-tg-shop-chap-redis-data:/data
    networks:
      - remnawave-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  remnawave-network:
    external: true

volumes:
  rw-tg-shop-chap-db-data:
    name: rw-tg-shop-chap-db-data
  rw-tg-shop-chap-redis-data:
    name: rw-tg-shop-chap-redis-data

